# fly.toml app configuration file generated for fundi on 2023-12-24T20:00:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fundi"
primary_region = "jnb"

[build]
  image = "nutty4616/fundistore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51OMxpbFpTRtzNIWIj5IfsYlL8SNSyft5LSP2cDW2icdpxUqCxRL3ls0O9pViZlztCLBpQJh8L4i9u25gxgUkt8NB004S1RHIM5"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
